version: "3.8"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat-api
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    #image: elasticsearch:8.5.1
    container_name: elastic
    environment:
      #- node.name=elastic
      #- cluster.name=es-docker-cluster
      #- cluster.initial_master_nodes=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      #- xpack.monitoring.enabled=false
      #- xpack.graph.enabled=false
      #- xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/share/elasticsearch/data
      #- /usr/share/elasticsearch/config
    ports:
      - "9200:9200"
    command: elasticsearch

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - app_data:/app
    depends_on:
      - db
      - redis
      - elastic
    environment:
      DB_USER: root
      DB_NAME: chat-api
      DB_PASSWORD: password
      DB_HOST: db
      REDIS_URL: redis://redis:6379
      ES_URL: http://elastic:9200
      #ES_URL: "http://127.0.0.1:9200"

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elastic
    links:
      - db
      - redis
      - elastic
    volumes:
      - app_data:/app
    environment:
      DB_USER: root
      DB_NAME: chat-api
      DB_PASSWORD: password
      DB_HOST: db
      REDIS_URL: redis://redis:6379
      ES_URL: http://elastic:9200
      #ES_URL: "http://127.0.0.1:9200"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b
      '0.0.0.0'"

volumes:
  db: null
  elastic_data: null
  app_data: null
